module.exports = {
    email: 'BiTo',
    password: 'xxx',
    address: '',
    url: 'https://lbm245.racevietnam.com',
    urls: [
        'https://lbm245.racevietnam.com',
        'https://racevietnam.com',
        'https://lbm241.racevietnam.com',
        'https://lbm242.racevietnam.com',
        'https://lbm243.racevietnam.com',
        'https://lbm244.racevietnam.com',
    ],
    headless: false,
    loginURL: '/user/signverify?username=',
    ticketURL: '/longbien-marathon-2024-84/register',
    distance: 21,
    district: 'Chương Mỹ',
    commune: 'Hợp Đồng',
    bibName: 'TaNoBi',
    sos: 'Hường - 0966155592',
    size: 'M',
    blood: 'A+',
    hearth: 'Không',
    phone: 'xxxx',
    cardNumber: 'xxx',
    cardPass: 'xxx'
}